### ISSUE TITLE
Instance: SlicerMorph Evo2024 Workshop

### ISSUE THREAD

**Issue by jacqgarnett** [MorphoCloud/MorphoCloudInstances#16]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

I am a PhD candidate in Washington University in St. Louis working on 3D morphometrics of extant primates. I use photogrammetry to create 3D models and will have 100+ specimens. 

### ORCID

0009-0008-4156-4570

### Email

j.garnett@wustl.edu

**Comment by muratmaga** [comment]
./create
