### ISSUE TITLE
Instance: morphVQ Consistent Zoomout Refinement

### ISSUE THREAD

**Issue by oothomas** [MorphoCloud/MorphoCloudInstances#36]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

Using MATLAB to refine learned mouse mandible correspondences.

### ORCID

0000-0003-3500-5445

### Email

oshane.thomas@seattlechildrens.org

**Comment by muratmaga** [comment]
you already have another instance created.
https://github.com/MorphoCloud/MorphoCloudInstances/issues/31
Please use that
