### ISSUE TITLE
Instance: PMG MorphoTest

### ISSUE THREAD

**Issue by PaulGignac** [MorphoCloud/MorphoCloudInstances#40]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

I am trialing 3D rendering via a relatively small-screen laptop for Monday's MorphoCloud PI meeting.

### ORCID

0000-0001-9181-3258

### Email

pgignac@arizona.edu

**Comment by muratmaga** [comment]
there is something wrong we are looking into

**Comment by PaulGignac** [comment]
Thanks!

**Comment by muratmaga** [comment]
Dear MorphoCloud User,

We want to inform you that the current MorphoCloudInstances production service will be suspended on **June 1, 2026**. After that date, instances on the current platform will no longer be accessible.

We expect the new replacement platform to be operational by **July 1, 2026**, and potentially as early as before that date.

This transition is a hard reset:
- No instances, data, settings, or configurations from the current platform will be migrated.
- All users will need to onboard again when the new platform becomes available.

We understand this is a significant change. This reset is necessary to provide a stronger long-term foundation with:
- More flexibility in how you manage your instances
- Greater user control
- Improved privacy protections

The new platform will continue to run on GitHub and use the same control commands you already use. The key change is that we are moving to a GitHub organization model, and repositories will be accessible only to users who are members of the MorphoCloud organization.

If you would like to familiarize yourself in advance, draft onboarding instructions (subject to change) are available at https://github.com/MorphoCloud/docs. We will announce enrollment availability on the SlicerMorph/MorphoCloud mailing list. If you are not on that mailing list, please sign up at http://bit.ly/SM-listserv.
