### ISSUE TITLE
Instance: Test MorphoCloud for PhysiCell Studio; Randy Heiland

### ISSUE THREAD

**Issue by rheiland** [MorphoCloud/MorphoCloudInstances#57]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

Julian Pistorius recommended that I explore MorphoCloud as a possible option for a Web-based alternative to our PhysiCell Studio desktop application. Our application simulates multicellular agent based models and will be used in a 5-year NCI-funded project.

### ORCID

0000-0002-7440-2905

### Email

U2FsdGVkX1/htyzFXBvVVkFDWraP8LXznZbbpdHhznE=

**Comment by muratmaga** [comment]
Thank you for your interest. I am not sure how exactly this may work out for you, as we have very specific use (interactive 3D visualization and data processing). In any event, I approved your request. You should shortly receive the access credentials and short usage instructions in your email. Please do check this document, if you haven't done so: https://docs.google.com/document/d/1WRds-QWnDK1MnmEhGUPyBgjE9hitiddcElAPWiAYRg4/edit?tab=t.0#heading=h.b0yi3m7wlfk8

**Comment by jcfr** [comment]
To accommodate both possible future delay in jetstream provisioning time and increase provisioning time following the installation of SlicerMorph dependencies during provisioning, I further increased the polling timeout. See https://github.com/MorphoCloud/MorphoCloudInstances/commit/3761333c3657d4141981bf5f8eda971f52cbdfcf

**Comment by muratmaga** [comment]
Dear MorphoCloud User,

We want to inform you that the current MorphoCloudInstances production service will be suspended on **June 1, 2026**. After that date, instances on the current platform will no longer be accessible.

We expect the new replacement platform to be operational by **July 1, 2026**, and potentially as early as before that date.

This transition is a hard reset:
- No instances, data, settings, or configurations from the current platform will be migrated.
- All users will need to onboard again when the new platform becomes available.

We understand this is a significant change. This reset is necessary to provide a stronger long-term foundation with:
- More flexibility in how you manage your instances
- Greater user control
- Improved privacy protections

The new platform will continue to run on GitHub and use the same control commands you already use. The key change is that we are moving to a GitHub organization model, and repositories will be accessible only to users who are members of the MorphoCloud organization.

If you would like to familiarize yourself in advance, draft onboarding instructions (subject to change) are available at https://github.com/MorphoCloud/docs. We will announce enrollment availability on the SlicerMorph/MorphoCloud mailing list. If you are not on that mailing list, please sign up at http://bit.ly/SM-listserv.
