### ISSUE TITLE
Instance: Volume compressed into ROI

### ISSUE THREAD

**Issue by OwenProulx** [MorphoCloud/MorphoCloudInstances#69]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

I (Owen Proulx) have been having this issue for the past few weeks. When I load reconstruction files into slicer, I get this series of errors:
Python 3.9.10 (main, Apr 5 2024, 01:02:26) [MSC v.1938 64 bit (AMD64)] on win32

[Qt] libpng warning: iCCP: profile ‘ICC Profile’: ‘CMYK’: invalid ICC profile color space

[Qt] libpng warning: iCCP: known incorrect sRGB profile

[FD] TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.

[FD] TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.

[FD] TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.

[FD] TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.

If I continue to create and render and ROI, the whole volume gets compressed into the ROI, squishing it. (pics attached)
![Screenshot 2024-11-12 150906](https://github.com/user-attachments/assets/c5c7a48e-1c88-437e-bb1d-8d906c11d061)
![Screenshot 2024-11-12 151357](https://github.com/user-attachments/assets/74b4cab8-d919-46ba-81df-d1a848dd19cd)

### ORCID

0009-0002-7381-5748

### Email

U2FsdGVkX19r9iP5XbEgkivLCu3eXsubUkLiL1UsOdc=

### Confirm Email

U2FsdGVkX19r9iP5XbEgkivLCu3eXsubUkLiL1UsOdc=

**Comment by muratmaga** [comment]
Dear MorphoCloud User,

We want to inform you that the current MorphoCloudInstances production service will be suspended on **June 1, 2026**. After that date, instances on the current platform will no longer be accessible.

We expect the new replacement platform to be operational by **July 1, 2026**, and potentially as early as before that date.

This transition is a hard reset:
- No instances, data, settings, or configurations from the current platform will be migrated.
- All users will need to onboard again when the new platform becomes available.

We understand this is a significant change. This reset is necessary to provide a stronger long-term foundation with:
- More flexibility in how you manage your instances
- Greater user control
- Improved privacy protections

The new platform will continue to run on GitHub and use the same control commands you already use. The key change is that we are moving to a GitHub organization model, and repositories will be accessible only to users who are members of the MorphoCloud organization.

If you would like to familiarize yourself in advance, draft onboarding instructions (subject to change) are available at https://github.com/MorphoCloud/docs. We will announce enrollment availability on the SlicerMorph/MorphoCloud mailing list. If you are not on that mailing list, please sign up at http://bit.ly/SM-listserv.
